#声明使用的语言
language: java

# 声明使用的JDK版本
jdk:
  - openjdk8

os: Ubuntu Xenial

# 声明所需的服务
services:
  - mysql

# 指定使用的软件版本
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

# 通知方式
notifications:
  email: false
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=ff6a643a4136857bcb532a4f6eb606fafb93b69dccabcba3d0c551102e943b9e

# 执行脚本之前创建数据库
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS schedule default charset utf8 COLLATE utf8_general_ci;'

# 执行脚本
script:
  - cd api
  - cd schedule
  - java -version
  - javac -version
  - mvn test
