version: "3.0"

services:
  schedule-web:
    image: nginx
    ports:
      - 17801:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - schedule-api
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M

  schedule-api:
    image: adoptopenjdk/openjdk8:jre8u282-b08-debian
    depends_on:
      - schedule-db
    command: "bash /opt/app/start.sh"
    working_dir: "/opt/app"
    volumes:
      - ./api:/opt/app
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  schedule-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=schedule
      - MYSQL_DATABASE=schedule
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 17361:3306
    expose:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M