spring:
  profiles:
    active: ${active:travis}
  h2:
    console:
      enabled: true
  session:
    store-type: hash_map
server:
  port: 8080
---
spring:
  profiles:test

---
spring:
  profiles: travis
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/${dbname:schedule}?characterEncoding=UTF-8
    username: ${username:root}
    password: ${password:}

---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:${dbport:3306}/${dbname:schedule}?characterEncoding=UTF-8
    username: ${username:root}
    password: ${password:}



